/* By Allister Moon, September 2014
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
// Answer: 4613732

#include <iostream>
using namespace std;


int main() {

    int sum = 0;
    int prevNum = 1;
    int currNum = 1;

    while(currNum <= 4000000) {
        if(currNum % 2 == 0) sum += currNum;

        currNum += prevNum;
        prevNum = currNum - prevNum;
    }

    cout << sum << endl;
    return 0;
}
